site_name: PyMdDoc
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt 
  features:
    - content.code.copy
repo_url: https://github.com/devincornell/pymddoc
repo_name: devincornell/pymddoc

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

